/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const websharedmemory_new: (a: number) => number;
export const websharedmemory_get_ptr: (a: number) => number;
export const websharedmemory_get_commands_ptr: (a: number) => number;
export const websharedmemory_get_game_structure_game_ptr: (a: number) => number;
export const websharedmemory_get_game_structure_control_ptr: (a: number) => number;
export const websharedmemory_get_commands_offsets: (a: number) => any;
export const websharedmemory_get_game_state_offsets: (a: number) => any;
export const websharedmemory_get_default_game_state: (a: number) => any;
export const __wbg_websharedmemory_free: (a: number, b: number) => void;
export const refresh_rate_hz: () => number;
export const shared_game_state_byte_size: () => number;
export const create_shared_memory_wasm: () => number;
export const wasm_bindgen__closure__destroy__hea883acee0d0ae9c: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0218688814f3a132: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hdfb3f8470b6e288d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd9047163655ea713: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hf0d2fbce5e37e975: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ed2f9b69b8a5af_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2b76460ec8b3b9f6: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2fa51b51e517bbd9: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__ha46cfec17c58cfce: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h235191981a82163f: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
