/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const websharedmemory_new: (a: number) => number;
export const websharedmemory_get_commands_ptr: (a: number) => number;
export const websharedmemory_get_game_structure_game_ptr: (a: number) => number;
export const websharedmemory_get_game_structure_control_ptr: (a: number) => number;
export const websharedmemory_get_frame_buffer_write_head_ptr: (a: number) => number;
export const websharedmemory_get_frame_buffer_entries_ptr: (a: number) => number;
export const websharedmemory_get_frame_buffer_entry_stride: (a: number) => number;
export const websharedmemory_get_frame_buffer_size: (a: number) => number;
export const websharedmemory_get_commands_offsets: (a: number) => any;
export const websharedmemory_get_game_state_offsets: (a: number) => any;
export const websharedmemory_get_default_game_state: (a: number) => any;
export const __wbg_websharedmemory_free: (a: number, b: number) => void;
export const refresh_rate_hz: () => number;
export const shared_game_state_byte_size: () => number;
export const create_shared_memory_wasm: () => number;
export const websharedmemory_get_ptr: (a: number) => number;
export const wasm_bindgen__closure__destroy__h008ef40e414b05ea: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1460c50773e8b475: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h7f28661cd7c808ff: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h75024a8abfa83955: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__heace45efc15e9340: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h05be767a89874804_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h79af2cf5ebf3e6cc: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h14051faa26fee3bc: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h985676e499e3a96b: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
