/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const websharedmemory_new: (a: number) => number;
export const websharedmemory_get_commands_ptr: (a: number) => number;
export const websharedmemory_get_game_structure_game_ptr: (a: number) => number;
export const websharedmemory_get_game_structure_control_ptr: (a: number) => number;
export const websharedmemory_get_commands_offsets: (a: number) => any;
export const websharedmemory_get_game_state_offsets: (a: number) => any;
export const websharedmemory_get_default_game_state: (a: number) => any;
export const __wbg_websharedmemory_free: (a: number, b: number) => void;
export const shared_game_state_byte_size: () => number;
export const create_shared_memory_wasm: () => number;
export const websharedmemory_get_ptr: (a: number) => number;
export const wasm_bindgen__closure__destroy__h02688f800ffa98c2: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hb69473973aca8f63: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0a6b5c9295a7ff96: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h576e55311a1ea04a: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h20ee923051ec38af: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hf81ad7ef3630a9f7: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hcdd381c35daa61ea: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10999c306299fdd8: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h70b77d51203f2fd1: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
