[workspace]
resolver = "2"
members = [
    "shared",
    "game_node",
]

[profile.dev]
opt-level = 1          # keep it debug-friendly
debug = 2              # good debug info
debug-assertions = true
overflow-checks = true
lto = "off"
codegen-units = 16
incremental = true
strip = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = 0
debug-assertions = false
opt-level = 3
lto = "fat"
strip = true
panic = "abort"

[profile.wasm-release]
inherits = "release"
debug = 0
debug-assertions = false
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[profile.wasm-dev]
inherits = "dev"
opt-level = 0          # keep it debug-friendly
debug = 2              # good debug info
debug-assertions = true
overflow-checks = true
lto = "off"
codegen-units = 16
incremental = true

# optional: keep dependencies not too crazy for wasm-dev
[profile.wasm-dev.package."*"]
opt-level = 0
